-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 15:17:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw-monson-university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw-monson-university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw-monson-university` DEFAULT CHARACTER SET utf8 ;
USE `dw-monson-university` ;

-- -----------------------------------------------------
-- Table `dw-monson-university`.`DIM_PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw-monson-university`.`DIM_PROFESSOR` (
  `id_professor` INT NOT NULL PRIMARY KEY,
  `nm_professor` VARCHAR(150),
  `status_professor` VARCHAR(50),
  `departamento` VARCHAR(75),
  `genero` VARCHAR(15)
);


-- -----------------------------------------------------
-- Table `dw-monson-university`.`DIM_CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw-monson-university`.`DIM_CURSO` (
  `id_curso` VARCHAR(15) NOT NULL PRIMARY KEY,
  `nm_curso` VARCHAR(150),
  `flag_pre_requisito` BOOLEAN,
  `modalidade` VARCHAR(50)
  );


-- -----------------------------------------------------
-- Table `dw-monson-university`.`DIM_TEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw-monson-university`.`DIM_TEMPO` (
  `inicio_referencia` DATETIME NOT NULL PRIMARY KEY,
  `dias_da_semana` VARCHAR(45),
  `mes` VARCHAR(45),
  `turno` VARCHAR(45),
  `flag_feriado` BOOLEAN
  );


-- -----------------------------------------------------
-- Table `dw-monson-university`.`FATO_AGENDAMENTO_CRONOGRAMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw-monson-university`.`FATO_AGENDAMENTO_CRONOGRAMA` (
  `id_cronograma` INT NOT NULL PRIMARY KEY,
  `id_professor` INT,
  `id_curso` VARCHAR(15),
  `qnt_dias_letivos` INT,
  `carga_horaria_minutos` INT,
  `qtd_alunos_aprovados` INT,
  `creditos_ofertados` INT,
  `flag_aula_auxiliada` BOOLEAN,
  `data_inicio` DATETIME NULL
  );

  ALTER TABLE FATO_AGENDAMENTO_CRONOGRAMA
    ADD FOREIGN KEY (id_professor) REFERENCES DIM_PROFESSOR(id_professor),
    ADD FOREIGN KEY (id_curso) REFERENCES DIM_CURSO(id_curso),
    ADD FOREIGN KEY (data_inicio) REFERENCES DIM_TEMPO(inicio_referencia);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
